### PR TITLE
Can not open the gate

### PR DESCRIPTION
**Pull request by DoreK333**
http://i.imgur.com/lRefllZ.png
Timings: https://timings.aikar.co/?id=7d5f5618f0fe44b9a6def0095f9e313f

### CODE REVIEW

**Comment by me4502** [comment]
So firstly.... why make a PR to submit an issue?

As for the gate, I can't quite see the sign, but does it say IRON_FENCE on the sign? Just making sure it has the right block.

I'll take a look into this, but that message normally means the gate needs more blocks stored in order to fully extend.

**Comment by DoreK333** [comment]
Yes, it is "IRON_FENCE".

**Comment by me4502** [comment]
Are there other iron fences near the sign? I can't reproduce the issue, so just wondering if it's a legitimate message from when there aren't enough fences to complete the gate.

**Comment by DoreK333** [comment]
There is no (only on the upper floor of the building).
In addition, a lot of players are complaining about the dead gate, and one of the players trying to create a gate (clicking on a sign) made a hole down.

**Comment by me4502** [comment]
Has anything changed on your server since it was working correctly? Gates haven't been changed in a while.

**Pull request closed without merging**
