### PR TITLE
Fixes duplication bug encountered with locking plugins.

### PR DESCRIPTION
**Pull request by Kowaman**

### CODE REVIEW

**Comment by me4502** [comment]
This does nothing - the first line filters them out (Unless the user has explicitly disabled it in the config)

**Comment by Kowaman** [comment]
I want to believe you, but when I tested this on my server it fixed the dupe. Testing with ModernLWC.

**Comment by Kowaman** [comment]
Wait, which config flag, I think that might be it haha

**Comment by Kowaman** [comment]
Yep I'm dumb haha

**Pull request closed without merging**
