### PR TITLE
Update ItemUtil.java

### PR DESCRIPTION
**Pull request by Platinteufel**
Complete isAFuel().

### CODE REVIEW

**Comment by Platinteufel** [comment]
Still to do for **getSmeletedResult**:

Stone Bricks -> Cracked Stone Bricks: 
https://minecraft.gamepedia.com/Smelting#Processing_ores_and_materials

Iron & Gold **tools, weapons and armor** -> Iron & Gold **nuggets**:
https://minecraft.gamepedia.com/Smelting#Tools.2C_weapons_and_armor

**Comment by me4502** [comment]
Thanks, is this finished or do you still wish to fix those other issues you mentioned?

**Comment by Platinteufel** [comment]
@me4502 It's finished from my side. Unfortunately I don't have enough knowledge about plugin development to fix those two points I've mentioned.

**Comment by me4502** [comment]
Ah, okay - thanks. I'll make those changes now then.

**Comment by Platinteufel** [comment]
Thank you :)

**Pull request merged**
