### PR TITLE
Fix a problem where self triggered ICs could cause chunk thrashing

### PR DESCRIPTION
**Pull request by DarkArc**
A [chunk monitor system I wrote](https://github.com/packet-loss-gaming/Grindstone/blob/master/src/main/java/gg/packetloss/grindstone/admin/ProblemDetectionComponent.java#L110-L188) to detect chunk thrashing and help prevent performance problems and disk wear detected issues with CraftBook's self triggered ICs.

The problem is effectively that an IC could check for input or set an output at cx +/-1, cz +/-1. This would then load the chunk, only for it to be quickly unloaded because it wasn't supposed to be running.

To resolve this, this patch "pauses" self triggered processing if any of the adjacent chunks are unloaded, waiting for a player to get closer.

### CODE REVIEW

**Comment by DarkArc** [comment]
To give some context to this problem, in one recent instance, this caused 400 unnecessary chunk loads within a minute, from a single IC (and this is not unusual).

**Comment by me4502** [comment]
This is meant to presumably target master?

**Comment by DarkArc** [comment]
Yeah, but I built it on the gradle-7 hotfix so it's targeting that instead for the moment.

Shouldn't be an issue with a cherry pick.

**Comment by me4502** [comment]
Needs a rebase on master

**Pull request merged**
