### PR TITLE
Fix block filter trait parsing and list generation

### PR DESCRIPTION
**Pull request by 14mRh4X0r**
As it is now, traits don't get parsed correctly (e.g. as `[color=whit` for `minecraft:wool[color=white]`), and the list generation loops endlessly when specifying the single trait of a block type.

However, due to [a bug in SpongeAPI](https://github.com/SpongePowered/SpongeAPI/issues/1835), this currently doesn't work when *not* specifying traits.

### CODE REVIEW

**Comment by me4502** [comment]
Thanks

**Comment by me4502** [comment]
Oh wait, do you mean this requires that Sponge fix first?

**Comment by 14mRh4X0r** [comment]
Yeah, sorry if I wasn't clear about that. Also, this will probably need adapting to SpongePowered/SpongeAPI#1811, once that's merged, but it looks like it belongs in API 8.

**Comment by me4502** [comment]
Would you be able to please re-make the PR? Reverted it because of me accidentally merging it.

**Pull request merged**
